### ISSUE TITLE
Error: cannot open file: decision_tree

### ISSUE THREAD

**Issue by nnahito** [Michedev/DecisionTreeNim#1]
I wanted to take advantage of "DecisionTreeNim" so I ran the `nimble install decisiontree` command.

The following message appears:
```
Warning: Package 'DecisionTree' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'DecisionTree.nim', but a file named 'task.nim' was found. This will be an error in the future.

Hint: If this is the primary source file in the package, rename it to 'DecisionTree.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'DecisionTree', then move it into a 'DecisionTree/' subdirectory. If it's a test file or otherwise not required to build the the package 'DecisionTree.nim', prevent its installation by adding `skipFiles = @["task.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
```

---

It was a warning, so I wrote the code without worrying about it and compiled it.
However, as shown below, an error occurs even though I just made an import.

```nim
import decision_tree
```

```
$ nim c -r sample.nim
Error: cannot open file: decision_tree
```

Nim Compiler Version 1.0.6

---

Is there any way to solve this?
Thank you.

**Comment by Michedev** [comment]
Hi,
thank you for the issue, in 1/2 days i'll give a shot since i have exams in this period

**Comment by nnahito** [comment]
Thank you for your prompt response.
Good luck on your exam!

**Comment by Michedev** [comment]
sorry for the long time to response but you know, the period.
I've installed the package in another pc and i've found no problems, i think the error is in your import, since it should be `import DecisionTree` instead of `import decision_tree`

Thank you for the issue, because i'll investigate on the warning got and i'll put some examples in readme.md!

**Comment by Michedev** [comment]
sorry for the long time to response but now here i am!
I've installed the package in another pc and i've found no problems, i think the error is in the import syntax, since it should be import DecisionTree instead of `import decision_tree`

`decision_tree` was correct for my local installation but not when installed in another pc via nimble

Thank you for the issue, i'll fix the examples and check the warning
